name: Build APK

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps
        run: |
          sudo apt update
          sudo apt install -y 
            zip unzip openjdk-17-jdk 
            autoconf automake libtool 
            pkg-config cmake 
            libffi-dev libssl-dev

      - name: Install python deps
        run: |
          python -m pip install --upgrade pip
          pip install Cython==0.29.36
          pip install buildozer
          pip install git+https://github.com/kivy/python-for-android.git

      - name: Create buildozer.spec
        run: |
          cat > buildozer.spec << 'EOF'
          [app]
          title = TechSupport
          package.name = techsupport
          package.domain = org.example
          source.dir = .
          source.include_exts = py,png,jpg,kv,atlas,ttf,txt,json
          version = 1.0

          requirements = python3,kivy

          orientation = portrait
          fullscreen = 1
          android.permissions = INTERNET

          android.api = 31
          android.minapi = 21
          android.ndk = 25b
          android.archs = arm64-v8a

          android.accept_sdk_license = True

          [buildozer]
          log_level = 2
          EOF

      - name: Clean
        run: rm -rf .buildozer

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: techsupport-apk
          path: bin/*.apk
